### ISSUE TITLE
Great wireframes

### ISSUE THREAD

**Issue by Chebotarev** [bencalabrese/pickup_tix#2]
Nice job breaking down the elements on the page into components. Keep in mind that the things marked `static` will probably need to also be contained in a component. Otherwise you might have trouble getting it to show up only on one page (since you'll be using react router)

**Comment by bencalabrese** [comment]
Thanks, Alex! I should have been clearer with the labeling on that- that
static content is still within the main Splash component, which will have
an associated route.
I'm still gonna factor it out into another component though, just to keep
it the organization a little cleaner.

Best,
Ben Calabrese
